name: 'buffett'
version: '0.0.2'
config-version: 2
profile: 'buffett'

# Verzeichnisse
model-paths: ["models"]
clean-targets: ["database"]
docs-paths: ["docs"] 

# Optionale Konfiguration
require-dbt-version: ">=1.0.0"
models:
  buffett:
    staging:
      materialized: table  # Standard für Staging-Modelle
      stg_trades:
        materialized: incremental  # Explizite Ausnahme für stg_trades
