name: 'bfett'
version: '0.3.0'
config-version: 2
profile: 'bfett'

# Verzeichnisse
model-paths: ["models"]
clean-targets: ["database"]
docs-paths: ["docs"] 

# Optionale Konfiguration
require-dbt-version: ">=1.0.0"
models:
  bfett:
    staging:
      materialized: table  # Standard für Staging-Modelle
      stg_trades:
        materialized: incremental  # Explizite Ausnahme für stg_trades
